name: main-check
on: push
jobs:
  main-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Install Poetry
        run:
          pip install poetry
      - name: Run linter
        run: 
          make lint
      - name: Run Tests
          make test