name: pytest
on: [push]
jobs:
  test-check:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
            pip3 install poetry
            poetry install
            pip3 install PyYAML
            pip3 install pytest
            poetry run pytest 
    - name: Code coverage
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: 7fe7856d8ce5b36e37781840f0d7c4af692f30960d85b6cffde622bed42407c1
      with:
        coverageCommand: poetry run pytest --cov=gendiff --cov-report xml
        debug: true